In [1]:
from gol_apis import RosterActivitiesService
from gol_apis import RosterTagService
from gol_apis import CheckScheduleService
from gol_apis import CrewMemberInfoService
import api_tools
from api_tools.setup import setup_crew_info_dataframe
from api_tools.setup import setup_checks_dataframe
from api_tools.setup import setup_tag_dataframe
from api_tools.setup import setup_activities_dataframe

from gol_logger import Logger
import pandas as pd
import multiprocessing as mp
import requests, time
from datetime import datetime as dt
from datetime import timedelta as td
from utils import funcs
from utils.progress import step
from utils.progress import BAR
from itertools import chain

from modules.generate_data import get_data_neolude
from modules.generate_data import get_rosters
from modules.generate_data import get_crew_info
from modules.generate_data import get_checks

import sys
from config.variables import user

In [2]:
# Dados Crew Info
crew = pd.read_csv('data/crew/crew_info.csv', sep=';', encoding='utf-8-sig')
crew.cif = crew.cif.astype(int).astype(str).str.zfill(8)
crew = crew[crew['funcao'].isin(['CMT', 'COP'])]
crew = crew[['cif', 'guerra', 'funcao', 'cargo', 'base']]
crew

           cif           guerra funcao cargo base
0     00000020            BORIO    CMT   IBX  CGH
1     00000021          GRABLER    CMT   IBX  GRU
2     00000022           DANTAS    CMT   IBX  CGH
3     00000024            BORBA    CMT   NaN  GRU
4     00000026  FERNANDO FARIAS    CMT   IBX  CGH
...        ...              ...    ...   ...  ...
5480  99999913           PIAZZA    CMT    IB  GRU
5481  99999916    GALENO CABRAL    CMT    IB  GRU
5482  99999917           EDWARD    CMT    IB  GRU
5483  99999918          CESIDIO    CMT    IB  GRU
5484  99999919             ZAGO    CMT    IB  GRU

[2033 rows x 5 columns]

In [3]:
# Header para filtrar dados do Neolude
header_neolude = ['RegistrationNumber',
                  'UserName',
                  'BusinessUnitName',
                  'Post',
                  'CPF',
                  'Email',
                  'CourseUserStatus',
                  'GradeFormatted',
                  'LastAccessDate',
                  'CreatedDate',
                  'CompletionDate']

In [4]:
# Dados Neolude
arp = pd.read_csv('data/neolude/ARP.csv', sep=';', encoding='utf-8-sig')
arp = arp[header_neolude]
arp['RegistrationNumber'] = arp['RegistrationNumber'].fillna(0)
arp['RegistrationNumber'] = arp['RegistrationNumber'].astype(int).astype(str).str.zfill(8)
arp['LastAccessDate'] = pd.to_datetime(arp['LastAccessDate'])
arp['CreatedDate'] = pd.to_datetime(arp['CreatedDate'])
arp['CompletionDate'] = pd.to_datetime(arp['CompletionDate'])
arp.columns = ['cif', 'name', 'base', 'funcao', 'cpf', 'email', 'status', 'nota', 'ultimo_acesso', 'criacao_acesso', 'data_conclusao']
arp = arp[['cif', 'status', 'nota', 'data_conclusao']]
arp

           cif     status   nota      data_conclusao
0     00025086  Concluído   9,56 2020-07-01 03:38:33
1     00043353  Concluído  10,00 2020-09-03 14:07:04
2     00044269  Concluído  10,00 2020-11-03 17:17:07
3     00017040  Concluído   9,40 2020-06-03 18:20:39
4     00000931  Concluído   9,41 2020-06-09 15:37:56
...        ...        ...    ...                 ...
1094  00008753  Concluído   9,78 2020-09-08 15:46:35
1095  00023148  Concluído  10,00 2020-09-02 16:03:10
1096  00001548  Concluído   9,00 2020-09-01 15:19:55
1097  00044238  Concluído   9,78 2020-05-06 14:24:39
1098  00038720  Concluído   9,78 2020-10-09 17:33:19

[1099 rows x 4 columns]

In [5]:
# Dados de Rosters
rosters = funcs.generate_data('data/rosters/')
rosters.cif = rosters.cif.astype(str).str.zfill(8)
rosters = rosters[rosters['code'].isin(funcs.training_filter('ARP'))]
rosters = rosters.sort_values(by=['cif','dep'])
rosters = rosters[['cif', 'code', 'fr', 'dep']]
rosters = rosters.drop_duplicates(subset = ['cif'], keep = 'last')
rosters

importing: 2020-01...
importing: 2020-02...
importing: 2020-03...
importing: 2020-04...
importing: 2020-05...
importing: 2020-06...
importing: 2020-07...
importing: 2020-08...
importing: 2020-09...
importing: 2020-10...
importing: 2020-11...

             cif       code   fr                  dep
152256  00000019   C-ARP-ON  CGH  2020-06-29 16:00:00
38689   00000020   C-ARP-ON  CGH  2020-06-08 16:00:00
33027   00000024  C-ENS-ARP  CGH  2020-05-07 16:30:00
87067   00000027   C-ARP-ON  CGH  2020-06-17 16:00:00
13366   00000029   C-ARP-ON  CGH  2020-09-03 16:30:00
...          ...        ...  ...                  ...
76488   00046079  C-ENS-ARP  CGH  2020-03-11 11:15:00
76316   00046080  C-ENS-ARP  CGH  2020-03-11 11:15:00
76334   00046081  C-ENS-ARP  CGH  2020-03-11 11:15:00
76408   00046082  C-ENS-ARP  CGH  2020-03-11 11:15:00
76416   00046119  C-ENS-ARP  CGH  2020-03-11 11:15:00

[4115 rows x 4 columns]

In [6]:
# Dados de Checks
checks = pd.read_csv('data/checks/check_schedule.csv', sep=';', encoding='utf-8-sig')
checks.cif = checks.cif.astype(str).str.zfill(8)
checks = checks[checks['checkTypeCode'] == 'ARP']
checks = checks[['cif', 'checkTypeCode', 'expiryDt']]
checks

            cif checkTypeCode    expiryDt
88     00005309           ARP  2021-05-26
93     00024283           ARP  2021-06-30
114    00003256           ARP  2021-06-18
134    00003659           ARP  2021-08-22
139    00034409           ARP  2021-01-23
...         ...           ...         ...
65490  00045803           ARP  2021-02-17
65491  00045793           ARP  2021-02-17
65492  00045777           ARP  2021-02-17
65493  00045774           ARP  2021-02-17
65494  00045802           ARP  2021-02-17

[4783 rows x 3 columns]

In [7]:
# Merge dos dados
resultado = pd.merge(crew, checks[['cif', 'checkTypeCode', 'expiryDt']], on='cif', how='left')
resultado = resultado.merge(arp, on='cif', how='left')
resultado = resultado.merge(rosters[['cif', 'code', 'dep']], on='cif', how='left')
resultado

,cif,guerra,funcao,cargo,base,checkTypeCode,expiryDt,status,nota,data_conclusao,code,dep
0,00000020,BORIO,CMT,IBX,CGH,ARP,2021-06-03,Concluído,"9,63",2020-06-03 14:54:28,C-ARP-ON,2020-06-08 16:00:00
1,00000021,GRABLER,CMT,IBX,GRU,ARP,2021-01-06,NaN,NaN,NaT,NaN,NaN
2,00000022,DANTAS,CMT,IBX,CGH,ARP,2021-06-20,NaN,NaN,NaT,NaN,NaN
3,00000024,BORBA,CMT,NaN,GRU,ARP,2021-05-06,Concluído,"9,84",2020-05-06 14:42:46,C-ENS-ARP,2020-05-07 16:30:00
4,00000026,FERNANDO FARIAS,CMT,IBX,CGH,ARP,2021-01-17,NaN,NaN,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2047,99999913,PIAZZA,CMT,IB,GRU,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2048,99999916,GALENO CABRAL,CMT,IB,GRU,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2049,99999917,EDWARD,CMT,IB,GRU,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2050,99999918,CESIDIO,CMT,IB,GRU,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2051,99999919,ZAGO,CMT,IB,GRU,NaN,NaN,NaN,NaN,NaT,NaN,NaN

In [8]:
# Formatação do dataFrame de Dados
validation = resultado.copy()
validation['dep'] = validation['dep'].fillna(pd.to_datetime(dt(2035,12,31)))
validation['data_conclusao'] = validation['data_conclusao'].fillna(pd.to_datetime(dt(2035,12,31)))
validation['dep'] = pd.to_datetime(validation['dep'], format='%Y-%m-%d')
validation['dep'] = validation['dep'].dt.floor('D')
validation['data_conclusao'] = pd.to_datetime(validation['data_conclusao'], format='%Y-%m-%d')
validation['data_conclusao'] = validation['data_conclusao'].dt.floor('D')
validation

,cif,guerra,funcao,cargo,base,checkTypeCode,expiryDt,status,nota,data_conclusao,code,dep
0,00000020,BORIO,CMT,IBX,CGH,ARP,2021-06-03,Concluído,"9,63",2020-06-03,C-ARP-ON,2020-06-08
1,00000021,GRABLER,CMT,IBX,GRU,ARP,2021-01-06,NaN,NaN,2035-12-31,NaN,2035-12-31
2,00000022,DANTAS,CMT,IBX,CGH,ARP,2021-06-20,NaN,NaN,2035-12-31,NaN,2035-12-31
3,00000024,BORBA,CMT,NaN,GRU,ARP,2021-05-06,Concluído,"9,84",2020-05-06,C-ENS-ARP,2020-05-07
4,00000026,FERNANDO FARIAS,CMT,IBX,CGH,ARP,2021-01-17,NaN,NaN,2035-12-31,NaN,2035-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...
2047,99999913,PIAZZA,CMT,IB,GRU,NaN,NaN,NaN,NaN,2035-12-31,NaN,2035-12-31
2048,99999916,GALENO CABRAL,CMT,IB,GRU,NaN,NaN,NaN,NaN,2035-12-31,NaN,2035-12-31
2049,99999917,EDWARD,CMT,IB,GRU,NaN,NaN,NaN,NaN,2035-12-31,NaN,2035-12-31
2050,99999918,CESIDIO,CMT,IB,GRU,NaN,NaN,NaN,NaN,2035-12-31,NaN,2035-12-31
2051,99999919,ZAGO,CMT,IB,GRU,NaN,NaN,NaN,NaN,2035-12-31,NaN,2035-12-31

In [9]:
# Variavel considerada para filtrar tripulantes com vencimentos nos proximos dois meses
venc_next_month = pd.to_datetime(dt.now()) + pd.offsets.MonthBegin(2)

In [10]:
# Tripulantes com vencimentos nos proximos dois meses, com treinamentos plotados em escala e 
# que já concluiram o curso
arp_atualizar = validation[(validation['dep'] < pd.to_datetime(dt.now())) &
                           (pd.to_datetime(validation['expiryDt']) < venc_next_month) &
                           (validation['status'] == 'Concluído')
                          ]
arp_atualizar

,cif,guerra,funcao,cargo,base,checkTypeCode,expiryDt,status,nota,data_conclusao,code,dep
54,00000455,CUNHA,CMT,NaN,GIG,ARP,2020-12-19,Concluído,"9,03",2020-11-15,C-ARP-ON,2020-11-15
161,00001615,LEONARDO MONTENEGRO,CMT,IR,CGH,ARP,2020-11-07,Concluído,"9,78",2020-11-05,C-ARP-ON,2020-11-06
260,00002367,TESSAROLO,CMT,IR,GRU,ARP,2020-09-05,Concluído,"9,62",2020-11-11,C-ARP-ON,2020-11-11
386,00003378,VIRGILIO VITALLI,CMT,IR,GRU,ARP,2020-10-10,Concluído,"9,78",2020-11-01,C-ARP-ON,2020-11-01
388,00003435,ALEXANDRE FERREIRA,CMT,NaN,SDU,ARP,2020-12-19,Concluído,"9,41",2020-11-02,C-ARP-ON,2020-11-10
460,00004472,FAUSTO KOVALEW,CMT,NaN,CGH,ARP,2020-11-28,Concluído,"8,78",2020-07-30,C-ARP-ON,2020-11-10
461,00004472,FAUSTO KOVALEW,CMT,NaN,CGH,ARP,2020-11-28,Concluído,"9,78",2020-11-08,C-ARP-ON,2020-11-10
614,00006390,DIMAS,CMT,NaN,GIG,ARP,2020-12-19,Concluído,"9,25",2020-11-04,C-ARP-ON,2020-11-09
621,00006463,SOLANO,CMT,NaN,FOR,ARP,2020-11-14,Concluído,"9,25",2020-11-01,C-ARP-ON,2020-11-01
675,00008179,HAMILTON NETO,CMT,IR,POA,ARP,2020-10-23,Concluído,"9,78",2020-11-01,C-ARP-ON,2020-11-06
736,00008738,PLINIO,CMT,IR,GRU,ARP,2020-12-20,Concluído,"9,68",2020-11-11,C-ARP-ON,2020-11-15
769,00009064,UBIRATAN SIMOES,CMT,NaN,GIG,ARP,2020-12-19,Concluído,"10,00",2020-11-02,C-ARP-ON,2020-11-01
978,00013071,VALERIA FACA,COP,NaN,GIG,ARP,2020-12-31,Concluído,"9,56",2020-11-10,C-ARP-ON,2020-11-12
1116,00023406,ALEX VIEIRA,COP,NaN,CGH,ARP,2020-12-13,Concluído,"9,56",2020-11-04,C-ARP-ON,2020-11-10
1159,00023695,GIOVANE FERNANDES,COP,NaN,GIG,ARP,2020-12-31,Concluído,"9,62",2020-11-04,C-ARP-ON,2020-11-15
1207,00024144,WANDERSON OLIVEIRA,COP,NaN,GIG,ARP,2020-12-31,Concluído,"9,62",2020-11-14,C-ARP-ON,2020-11-14
1279,00024481,ANDRE MACHADO,COP,NaN,CGH,ARP,2020-07-25,Concluído,"9,63",2020-07-21,C-ARP-ON,2020-07-22
1342,00024899,SALATIEL,COP,NaN,GRU,ARP,2020-10-24,Concluído,"9,33",2020-11-01,C-ARP-ON,2020-11-04
1504,00035137,JAMIL,COP,NaN,GRU,ARP,2020-09-20,Concluído,"8,53",2020-11-03,C-ARP-ON,2020-11-04
1561,00035480,RENAN TORRES,COP,NaN,BSB,ARP,2020-12-13,Concluído,"9,33",2020-11-07,C-ARP-ON,2020-11-07
1562,00035481,HAAG,COP,NaN,GRU,ARP,2020-12-13,Concluído,"9,33",2020-11-08,C-ARP-ON,2020-11-08
1563,00035482,ROBERTO RIBEIRO,COP,NaN,CGH,ARP,2020-12-13,Concluído,"8,59",2020-11-09,C-ARP-ON,2020-11-09
1571,00036101,THALES ABDO,COP,NaN,CGH,ARP,2020-12-20,Concluído,"9,52",2020-11-13,C-ARP-ON,2020-11-16
1699,00042971,VICTOR CAIO,COP,NaN,BSB,ARP,2020-11-06,Concluído,"9,78",2020-11-01,C-ARP-ON,2020-11-01
1813,00044231,LUCCAS FLAVIO,COP,NaN,CGH,ARP,2020-12-03,Concluído,"8,56",2020-11-11,C-ARP-ON,2020-11-11
1817,00044237,VARASQUIM,COP,NaN,CGH,ARP,2020-12-03,Concluído,"9,78",2020-11-13,C-ARP-ON,2020-11-16
1825,00044269,BULATY,COP,NaN,CGH,ARP,2020-12-03,Concluído,"10,00",2020-11-03,C-ARP-ON,2020-11-06
1844,00044360,MARCOS ALARCON,COP,NaN,GRU,ARP,2020-12-17,Concluído,"9,56",2020-11-04,C-ARP-ON,2020-11-10
1846,00044362,CARLOS GUASTALA,COP,NaN,GRU,ARP,2020-12-17,Concluído,"9,56",2020-11-01,C-ARP-ON,2020-11-12
1847,00044363,IGOR MAIA,COP,NaN,GIG,ARP,2020-12-17,Concluído,"9,07",2020-11-13,C-ARP-ON,2020-11-13
1849,00044365,BRUNO DINIZ,COP,NaN,GIG,ARP,2020-12-17,Concluído,"10,00",2020-11-08,C-ARP-ON,2020-11-08
1850,00044367,MADSEN,COP,NaN,GRU,ARP,2020-12-17,Concluído,"9,56",2020-11-11,C-ARP-ON,2020-11-14
1852,00044369,ANDRE PASINATO,COP,NaN,GRU,ARP,2020-12-17,Concluído,"9,62",2020-11-08,C-ARP-ON,2020-11-08
1853,00044370,ANDRE LARA,COP,NaN,GRU,ARP,2020-12-17,Concluído,"9,40",2020-11-11,C-ARP-ON,2020-11-11
1854,00044371,VINICIUS PALOMBINO,COP,NaN,GRU,ARP,2020-12-17,Concluído,"10,00",2020-11-05,C-ARP-ON,2020-11-09
1855,00044372,LUCAS LOURENCO,COP,NaN,GRU,ARP,2020-12-17,Concluído,"10,00",2020-11-08,C-ARP-ON,2020-11-09
1857,00044393,RAFAEL GOSSLER,COP,NaN,POA,ARP,2020-12-17,Concluído,"9,40",2020-11-12,C-ARP-ON,2020-11-12
1858,00044396,EGERTT,COP,NaN,GRU,ARP,2020-12-17,Concluído,"9,19",2020-11-05,C-ARP-ON,2020-11-05
1861,00044405,HELIO JUNIOR,COP,NaN,GRU,ARP,2020-12-17,Concluído,"9,84",2020-11-05,C-ARP-ON,2020-11-07
1863,00044413,CAZE,COP,NaN,GRU,ARP,2020-12-17,Concluído,"9,62",2020-11-07,C-ARP-ON,2020-11-07
1864,00044414,PEDRO ARAUJO,COP,NaN,GRU,ARP,2020-12-17,Concluído,"10,00",2020-11-02,C-ARP-ON,2020-11-13
1867,00044420,GABRIEL LIMA,COP,NaN,GRU,ARP,2020-12-17,Concluído,"9,56",2020-11-07,C-ARP-ON,2020-11-13
1870,00044424,CAIO CARVALHO,COP,NaN,GRU,ARP,2020-12-17,Concluído,"10,00",2020-11-05,C-ARP-ON,2020-11-07
1871,00044428,MIGUEL JUNIOR,COP,NaN,POA,ARP,2020-12-17,Concluído,"10,00",2020-11-09,C-ARP-ON,2020-11-09
1874,00044432,PEDRO GARCIA,COP,NaN,GRU,ARP,2020-12-17,Concluído,"9,78",2020-11-07,C-ARP-ON,2020-11-07
1876,00044435,ERIC CANTO,COP,NaN,GRU,ARP,2020-12-17,Concluído,"10,00",2020-11-03,C-ARP-ON,2020-11-03
1877,00044436,RAFAEL SCANTAMBURLO,COP,NaN,GRU,ARP,2020-12-17,Concluído,"9,41",2020-11-06,C-ARP-ON,2020-11-15
1879,00044440,NATHAN GOLLCHER,COP,NaN,GIG,ARP,2020-12-17,Concluído,"10,00",2020-11-02,C-ARP-ON,2020-11-10
1881,00044443,BORGHETTI,COP,NaN,GRU,ARP,2020-12-17,Concluído,"9,50",2020-11-11,C-ARP-ON,2020-11-16
1883,00044584,LEOVALDO,COP,NaN,GRU,ARP,2020-12-31,Concluído,"9,56",2020-11-12,C-ARP-ON,2020-11-12

In [11]:
arp_verificar =  validation[(validation['dep'] < pd.to_datetime(dt.now())) &
                            (pd.to_datetime(validation['expiryDt']) < venc_next_month) &
                            (validation['status'] != 'Concluído')
                           ]
arp_verificar

,cif,guerra,funcao,cargo,base,checkTypeCode,expiryDt,status,nota,data_conclusao,code,dep
154,00001593,MARCIO MIGUEIS,CMT,NaN,CGH,ARP,2016-12-31,NaN,NaN,2035-12-31,C-ARP-ON,2020-06-04
242,00002253,FABIO CASTRO,CMT,NaN,FOR,ARP,2020-09-05,Em andamento,"0,00",2035-12-31,C-ARP-ON,2020-11-04
252,00002352,CASSIO VEZZONI,CMT,IR,CGH,ARP,2020-10-24,Em andamento,"1,11",2035-12-31,C-ARP-ON,2020-10-06
295,00002840,CORTEZ,CMT,NaN,CGH,ARP,2020-12-13,NaN,NaN,2035-12-31,C-ARP-ON,2020-07-13
648,00007924,MACAHIBA,CMT,NaN,CGH,ARP,2017-08-31,NaN,NaN,2035-12-31,C-ARP-ON,2020-07-02
1010,00017650,PEDRO BASTOS,CMT,NaN,CGH,ARP,2020-12-06,Em andamento,"1,11",2035-12-31,C-ARP-ON,2020-11-16
1587,00036564,RUAN,COP,NaN,GIG,ARP,2020-12-31,Em andamento,"0,00",2035-12-31,C-ARP-ON,2020-11-16

In [12]:
arp_atualizar.to_csv('./data/output/arp_atualizar.csv', index=False, sep=';', encoding='utf-8-sig')
arp_verificar.to_csv('./data/output/arp_verificar.csv', index=False, sep=';', encoding='utf-8-sig')